# Generated by Django 5.1.2 on 2024-10-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_result_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
